// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1pTJNNcxo_s8APQUPvpPTT6SuxOGg5ks',
    appId: '1:763141285977:web:3cdecbda5fc3375e5ae948',
    messagingSenderId: '763141285977',
    projectId: 'petfeed-7b214',
    authDomain: 'petfeed-7b214.firebaseapp.com',
    databaseURL: 'https://petfeed-7b214-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'petfeed-7b214.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS3SkA2tdtrwqdHTF1ZjCnZoIA4lCwob8',
    appId: '1:763141285977:android:8ea9a30046f1c8255ae948',
    messagingSenderId: '763141285977',
    projectId: 'petfeed-7b214',
    databaseURL: 'https://petfeed-7b214-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'petfeed-7b214.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1pTJNNcxo_s8APQUPvpPTT6SuxOGg5ks',
    appId: '1:763141285977:web:b2738b31c3ee59525ae948',
    messagingSenderId: '763141285977',
    projectId: 'petfeed-7b214',
    authDomain: 'petfeed-7b214.firebaseapp.com',
    databaseURL: 'https://petfeed-7b214-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'petfeed-7b214.firebasestorage.app',
  );
}
